spring:
  application:
    name: bbanggu
  datasource:
    url: jdbc:mysql://localhost:3306/bbanggu?serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true


