server:
  error:
    include-stacktrace: never
spring:
  application:
    name: bbanggu
  datasource:
    url: jdbc:mysql://localhost:3306/bbanggu?serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: nagum0545@gmail.com
    password: ignervwducdxnlsu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
  mvc:
    content negotiation:
      favor-parameter: false
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

kakao:
  client-id: "3c52d7dbef8a4ac5ae57d0e59653b6a4"
  redirect-uri: "http://localhost:8080/oauth/kakao/callback"
  api-url:
    token: https://kauth.kakao.com/oauth/token
    user-info: https://kapi.kakao.com/v2/user/me

jwt:
  secret: WW91clNlY3VyZVJhbmRvbUtleTEyMzQ1
  expiration:
    access-token: 900000  # 15분 (밀리초)
    refresh-token: 86400000 # 24시간 (밀리초)
