server:
  error:
    include-stacktrace: never
spring:
  jackson:
    serialization:
      indent-output: true
  config:
    import: optional:file:.env[.properties]
  application:
    name: bbanggu
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: file:/home/ubuntu/uploads/
  jpa:
    # database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true  # JPA 초기화 후 `data.sql` 실행
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
#  sql:
#    init:
#      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
  mvc:
    content negotiation:
      favor-parameter: false
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

kakao:
  api:
    key: ${REST_API_KEY}
    url: https://dapi.kakao.com/v2/local/search/address.json
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  auth-uri: https://kauth.kakao.com/oauth/authorize
  api-url:
    token: https://kauth.kakao.com/oauth/token
    user-info: https://kapi.kakao.com/v2/user/me

jwt:
  secret: ${JWT_SECRET}
  expiration:
    access-token: 604800000 # 900000  # 15분 (밀리초)
    refresh-token: 604800000 # 7일 (밀리초)

toss:
  payments:
    api-key: ${TOSS_API_KEY}

openai:
  api-key: ${GPT_API_KEY}
