services:
  nginx:
    image: nginx:latest
    container_name: bbanggu-nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - bbanggu-network

networks:
  bbanggu-network:
    external: true
