version: '3.8'

services:
  app:
    build:
      context: ./bbanggu
      dockerfile: Dockerfile
      # args:
    container_name: bbanggu-server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - SERVER_PORT=8081
    networks:
      - bbanggu-network

  nginx:
    image: nginx:latest
    container_name: bbanggu-nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - bbanggu-network

networks:
  bbanggu-network:
    external: true
